version: 1.0.0.{build}

image: Visual Studio 2017

cache:
  - bdwgc.zip
  - win_flex_bison-latest.zip

environment:
  BDWGC_ARCHIVE: bdwgc.zip
  WINFLEXBISON_ARCHIVE: win_flex_bison-latest.zip

install:
  # install BDWGC and flex/bison
  - if not exist %BDWGC_ARCHIVE% appveyor DownloadFile "https://github.com/ivmai/bdwgc/archive/master.zip"
  - if not exist %WINFLEXBISON_ARCHIVE% appveyor DownloadFile "https://sourceforge.net/projects/winflexbison/files/%WINFLEXBISON_ARCHIVE%"
  - 7z x -y %BDWGC_ARCHIVE%
  - move bdwgc-master bdwgc
  - 7z x -y %WINFLEXBISON_ARCHIVE%
  - ren win_flex.exe flex.exe
  - ren win_bison.exe bison.exe
  - set PATH=.;%PATH%
  - flex --version
  - bison --version
 
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmake -G "NMake Makefiles" .
  - cmake --build . --config Release
