version: 1.0.0.{build}

image: Visual Studio 2017

cache:
  - win_flex_bison-latest.zip

environment:
  WINFLEXBISON_ARCHIVE: win_flex_bison-latest.zip

install:
  # install flex/bison
  - if not exist %WINFLEXBISON_ARCHIVE% appveyor DownloadFile "https://sourceforge.net/projects/winflexbison/files/%WINFLEXBISON_ARCHIVE%"
  - 7z x -y %WINFLEXBISON_ARCHIVE%
  - flex --version
  - bison --version
 
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - git clone https://github.com/ivmai/bdwgc.git
  - cmake -G "NMake Makefiles" . -D FLEX_EXECUTABLE=.\win_flex.exe -D BISON_EXECUTABLE=.\win_bison.exe
  - cmake --build . --config Release
